import { Data } from "../types/types";

const getData = (): Data[] => [
  {
    no: 1,
    image: "/menu/IMG-1.jpg",
    name: "Kopi Susu",
    description: "kopi susu ala kopi seruput",
    tag: "kopi sruput",
    price: 0,
  },
  {
    no: 2,
    image: "/menu/IMG-2.jpg",
    name: "Thai Mango Tea",
    description: "Thai Tea rasa mango ala teh seruput",
    tag: "teh sruput",
    price: 0,
  },
  {
    no: 3,
    image: "/menu/IMG-3.jpg",
    name: "Americano",
    description: "Americano ala kedai kopi seruput",
    tag: "kopi sruput",
    price: 0,
  },
  {
    no: 4,
    image: "/menu/IMG-4.jpg",
    name: "Ayam Kremes + Nasi",
    description: "Ayam kremes + nasi ala d'kremes",
    tag: "ayam d kremes",
    price: 0,
  },
  {
    no: 5,
    image: "/menu/IMG-5.jpg",
    name: "Ayam Kremes",
    description: "Ayam kremes satuan ala d'kremes",
    tag: "ayam d kremes",
    price: 0,
  },
  {
    no: 6,
    image: "/menu/IMG-6.jpg",
    name: "Sambal Bakar + Es teh",
    description: "Sambar bakar + Es teh jumbo",
    tag: "ayam d kremes",
    price: 15000,
  },
  {
    no: 7,
    image: "/menu/IMG-7.jpg",
    name: "Mie goreng keju",
    description: "Mie goreng keju ala kedai kopi seruput",
    tag: "kopi sruput",
    price: 0,
  },
  {
    no: 8,
    image: "/menu/IMG-8.jpg",
    name: "Americano",
    description: "Americano ala kedai kopi seruput",
    tag: "kopi sruput",
    price: 0,
  },
  {
    no: 9,
    image: "/menu/IMG-9.jpg",
    name: "Sambal Bakar + Es Teh",
    description: "Sambal Bakar komplit + Es teh Jumbo ala d'kremes",
    tag: "ayam d kremes",
    price: 0,
  },
  {
    no: 10,
    image: "/menu/IMG-10.jpg",
    name: "something",
    description: "nanti dah",
    tag: "kopi sruput",
    price: 0,
  },
  {
    no: 11,
    image: "/menu/IMG-11.jpg",
    name: "something",
    description: "nanti dah",
    tag: "kopi sruput",
    price: 0,
  },
  {
    no: 12,
    image: "/menu/IMG-12.jpg",
    name: "Ketan",
    description: "nanti dah",
    tag: "kopi sruput",
    price: 0,
  },
  {
    no: 13,
    image: "/menu/IMG-13.jpg",
    name: "something",
    description: "nanti dah",
    tag: "ayam d kremes",
    price: 0,
  },
  {
    no: 14,
    image: "/menu/IMG-14.jpg",
    name: "Nasi Goreng",
    description: "nanti dah",
    tag: "kopi sruput",
    price: 0,
  },
  {
    no: 15,
    image: "/menu/IMG-15.jpg",
    name: "something",
    description: "nanti dah",
    tag: "kopi sruput",
    price: 0,
  },
  {
    no: 16,
    image: "/menu/IMG-16.jpg",
    name: "something",
    description: "nanti dah",
    tag: "kopi sruput",
    price: 0,
  },
  {
    no: 17,
    image: "/menu/IMG-17.jpg",
    name: "Es teh jumbo",
    description: "nanti dah",
    tag: "teh sruput",
    price: 0,
  },
  {
    no: 18,
    image: "/menu/IMG-18.jpg",
    name: "Pink Lava Jumbo",
    description: "nanti dah",
    tag: "teh sruput",
    price: 0,
  },
  {
    no: 19,
    image: "/menu/IMG-19.jpg",
    name: "something",
    description: "nanti dah",
    tag: "kopi sruput",
    price: 0,
  },
  {
    no: 20,
    image: "/menu/IMG-20.jpg",
    name: "Jeruk",
    description: "nanti dah",
    tag: "teh sruput",
    price: 0,
  },
  {
    no: 21,
    image: "/menu/IMG-21.jpg",
    name: "Coklat",
    description: "nanti dah",
    tag: "kopi sruput",
    price: 0,
  },
  {
    no: 22,
    image: "/menu/IMG-22.jpg",
    name: "Lemon",
    description: "nanti dah",
    tag: "teh sruput",
    price: 0,
  },
  {
    no: 23,
    image: "/menu/IMG-23.jpg",
    name: "something",
    description: "nanti dah",
    tag: "teh sruput",
    price: 0,
  },
  {
    no: 24,
    image: "/menu/IMG-24.jpg",
    name: "Pink Lava Jumbo",
    description: "nanti dah",
    tag: "teh sruput",
    price: 0,
  },
  {
    no: 25,
    image: "/menu/IMG-25.jpg",
    name: "Pink Lava Jumbo",
    description: "nanti dah",
    tag: "teh sruput",
    price: 0,
  },
];

export default getData;
